<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <WarningsAsErrors>3239;0025</WarningsAsErrors>
        <PackageId>Partas.Solid.FablePlugin</PackageId>
        <Title>Partas.Solid.FablePlugin</Title>
        <RootNamespace>Partas.Solid</RootNamespace>
        <AssemblyNamespace>Partas.Solid.FablePlugin</AssemblyNamespace>
        <PackageTags>Partas;F#;FSharp;Plugin;fable-javascript;Compiler;Fable;Solid;Solidjs</PackageTags>
        <Company>F# Community</Company>
        <Description>Fable plugin; an opinionated derivative of Oxpecker.Solid.FablePlugin</Description>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Authors>Shayan Habibi based on work by Vladimir Schur and contributors</Authors>
        <Copyright>Copyright (c) Shayan Habibi 2025</Copyright>
        <Version>2.1.2</Version>
        <PackageVersion>2.1.2</PackageVersion>
    </PropertyGroup>
    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="\" />
        <Compile Include="Utils.fs" />
        <Compile Include="Types.fs" />
        <Compile Include="Spec.fs" />
        <Compile Include="Plugin.fs" />
        <Compile Include="Storybook.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Fable.AST" Version="5.0.0-beta.2" />
      <PackageReference Update="FSharp.Core" Version="8.0.400" />
    </ItemGroup>

</Project>
